### ISSUE TITLE
AssertionError - When run cleanser.py

### ISSUE THREAD

**Issue by cliefsengkey** [gouwsmeister/TextCleanser#2]
Hello Sir,

I'm try to run your programs, but there is an Assertion error. What's that mean sir?
I'm planning to attempt this for my research works now, related to normalize tweets data. The message looks like this : 

```
python cleanser.py 
Traceback (most recent call last):
  File "cleanser.py", line 85, in <module>
    tc = TextCleanser()
  File "cleanser.py", line 19, in __init__
    self.decoder = Decoder()
  File "/Users/cliefsengkey/Dropbox/RESEARCH-LDA/LDA-GENSIM/TextCleanser/decoder.py", line 27, in __init__
    assert os.path.exists(LATTICE_TOOL_DIR + "lattice-tool")
AssertionError
```

Thank You,

**Comment by ronilp** [comment]
Check the value of LATTICE_TOOL_DIR. It should contain '/' in the end
